In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor,AdaBoostRegressor
from sklearn.svm import SVR
from sklearn.linear_model import LinearRegression,Ridge,Lasso
from sklearn.model_selection import RandomizedSearchCV
from catboost import CatBoostRegressor
from xgboost import XGBRegressor

In [5]:
df=pd.read_csv('data/stud.csv')

In [6]:
df.head()

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [7]:
x=df.drop('math_score',axis=1)

In [8]:
y=df['math_score']

In [9]:
from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.compose import ColumnTransformer

In [10]:
Onehotenc=OneHotEncoder(drop='first')
scaler=StandardScaler()

In [11]:
cat_feature=x.select_dtypes(include='O').columns
num_feature=x.select_dtypes(exclude='O').columns

In [12]:
cat_feature,num_feature

(Index(['gender', 'race_ethnicity', 'parental_level_of_education', 'lunch',
        'test_preparation_course'],
       dtype='object'),
 Index(['reading_score', 'writing_score'], dtype='object'))

In [13]:
preprocessing=ColumnTransformer(
    [
        ("one hot encoder",Onehotenc,cat_feature),
        ("standard scaler",scaler,num_feature)
    ]
)

In [14]:
x=preprocessing.fit_transform(x)

In [15]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [17]:
def evaulation_matrix(true_data,predicted_data):
    r_score=r2_score(true_data,predicted_data)
    mae=mean_absolute_error(true_data,predicted_data)
    mse=mean_squared_error(true_data,predicted_data)
    rmse=np.sqrt(mse)
    
    return r_score,mae,mse,rmse

In [18]:
models={
    "k neighbour regression":KNeighborsRegressor(),
    "decision tree":DecisionTreeRegressor(),
    "random forest ":RandomForestRegressor(),
    "ada boost":AdaBoostRegressor(),
    "svr":SVR(),
    "linear regression":LinearRegression(),
    "ridge":Ridge(),
    "Lasso":Lasso()
}

In [21]:
for name,model in models.items():
    model.fit(x_train,y_train)
    y_train_pred=model.predict(x_train)
    y_test_pred=model.predict(x_test)
    
    print("\n\nmodel is :",name)
    print("\nscore of actual data:")
    r_score,mae,mse,rmse=evaulation_matrix(y_train,y_train_pred)
    print("\nr2 score is : ",r_score)
    print("mae is : ",mae)
    print("mse is : ",mse)
    print("rmse is : ",rmse)
    
    print("\n\nscore of predicted data:")
    r_score,mae,mse,rmse=evaulation_matrix(y_test,y_test_pred)
    print("\nr2 score is : ",r_score)
    print("mae is : ",mae)
    print("mse is : ",mse)
    print("rmse is : ",rmse)

model is : k neighbour regression

score of actual data:

r2 score is :  0.8624917023532732
mae is :  4.4510000000000005
mse is :  31.0009
rmse is :  5.567845184629329


score of predicted data:

r2 score is :  0.7763353420586311
mae is :  5.710999999999999
mse is :  54.4262
rmse is :  7.377411470156725


model is : decision tree

score of actual data:

r2 score is :  0.9996534669718089
mae is :  0.01875
mse is :  0.078125
rmse is :  0.2795084971874737


score of predicted data:

r2 score is :  0.7456422825168572
mae is :  6.325
mse is :  61.895
rmse is :  7.867337542015088


model is : random forest

score of actual data:

r2 score is :  0.9770877181495393
mae is :  1.8133958333333333
mse is :  5.165516340277777
rmse is :  2.272777230675672


score of predicted data:

r2 score is :  0.8550085668592928
mae is :  4.580541666666667
mse is :  35.28198335416667
rmse is :  5.939863917142098


model is : ada boost

score of actual data:

r2 score is :  0.8456045143333603
mae is :  4.843865014494354
mse is :  34.80807408364325
rmse is :  5.8998367844918596


score of predicted data:

r2 score is :  0.8519013537596947
mae is :  4.624938658498363
mse is :  36.03808761828193
rmse is :  6.003173129127789


model is : svr

score of actual data:

r2 score is :  0.7981779427964687
mae is :  4.983076233434738
mse is :  45.50027540327044
rmse is :  6.745389195833732


score of predicted data:

r2 score is :  0.713014089896163
mae is :  5.5045662322955105
mse is :  69.83469218721152
rmse is :  8.356715394651868


model is : linear regression

score of actual data:

r2 score is :  0.8743172040139593
mae is :  4.266711846071957
mse is :  28.33487038064859
rmse is :  5.323050852720514


score of predicted data:

r2 score is :  0.8804332983749565
mae is :  4.21476314247485
mse is :  29.095169866715477
rmse is :  5.393993869732841


model is : ridge

score of actual data:

r2 score is :  0.8742958408729106
mae is :  4.26499167177652
mse is :  28.339686647089753
rmse is :  5.323503230682757


score of predicted data:

r2 score is :  0.8804513937125635
mae is :  4.212514888062383
mse is :  29.090766576214737
rmse is :  5.393585688223998


model is : Lasso

score of actual data:

r2 score is :  0.8071462015863456
mae is :  5.206302661246528
mse is :  43.47840400585579
rmse is :  6.593815587795566


score of predicted data:

r2 score is :  0.8253197323627852
mae is :  5.157881810347763
mse is :  42.50641683841163
rmse is :  6.519694535667421